[package]
name = "astra-msbt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
astra_formats = { git = "https://github.com/thane98/astra-formats" }
